"""shopping_list=[]
shopping_list.append("键盘")
shopping_list.append("键帽")
shopping_list.remove("键帽")
print(shopping_list)"""
price=[100,666,999,1778]
max_price=max(price)
min_price=min(price)
sorted_price=sorted(price)
print(max_price)
print(min_price)
print(sorted_price)